# ---- Версия артефактов фреймворка ----
outboxVersion=1.0.0-SNAPSHOT

# ---- Производительность сборки ----
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=768m -XX:+UseParallelGC

# ---- Тесты ----
junit.jupiter.execution.parallel.enabled=true
