<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>thelameres</groupId>
    <artifactId>outbox-framework</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <java.version>25</java.version>
        <outbox-framework.version>0.0.1-SNAPSHOT</outbox-framework.version>
    </properties>

    <modules>
        <!-- Shared (Phase 1) -->
        <module>txbox-core</module>
        <module>txbox-jpa</module>
        <module>txbox-kafka</module>

        <!-- Producer (Phase 2) -->
        <module>txbox-consumer</module>
        <module>txbox-producer</module>

    </modules>

    <dependencyManagement>
        <dependencies>
            <!-- Shared (Phase 1) -->
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-core</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-jpa</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-kafka</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <!-- Producer (Phase 2) -->
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-producer-api</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-producer-jpa</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-producer-kafka</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-producer-starter</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <!-- Consumer (Phase 3) -->
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-consumer-api</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-consumer-jpa</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-consumer-kafka</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
            <dependency>
                <groupId>thelameres</groupId>
                <artifactId>txbox-consumer-starter</artifactId>
                <version>${outbox-framework.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                    <execution>
                        <id>default-testCompile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>testCompile</goal>
                        </goals>
                        <configuration>
                            <annotationProcessorPaths>
                                <path>
                                    <groupId>org.projectlombok</groupId>
                                    <artifactId>lombok</artifactId>
                                </path>
                            </annotationProcessorPaths>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
