<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>thelameres</groupId>
        <artifactId>outbox-framework</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>txbox-consumer</artifactId>
    <packaging>pom</packaging>
    <name>TxBox :: Consumer</name>
    <description>Transactional Inbox consumer-side modules</description>

    <modules>
        <module>txbox-consumer-api</module>
        <module>txbox-consumer-jpa</module>
        <module>txbox-consumer-kafka</module>
        <module>txbox-consumer-starter</module>
    </modules>

</project>
