<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>thelameres</groupId>
        <artifactId>txbox-consumer</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>txbox-consumer-kafka</artifactId>
    <name>TxBox :: Consumer :: Kafka</name>
    <description>Kafka listener and dispatcher for inbox: InboxKafkaListener, InboxEventDispatcher</description>

    <dependencies>
        <dependency>
            <groupId>thelameres</groupId>
            <artifactId>txbox-consumer-api</artifactId>
        </dependency>
        <dependency>
            <groupId>thelameres</groupId>
            <artifactId>txbox-consumer-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>thelameres</groupId>
            <artifactId>txbox-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-kafka</artifactId>
        </dependency>
    </dependencies>

</project>
