[versions]
springBoot = "4.1.1"
java       = "21"
lombok     = "1.18.46"
archunit   = "1.4.1"
nullaway   = "0.12.7"
errorprone = "2.38.0"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
lombok                   = { module = "org.projectlombok:lombok",                           version.ref = "lombok"     }
jspecify                 = { module = "org.jspecify:jspecify",                              version = "1.0.0"          }
archunit-junit5          = { module = "com.tngtech.archunit:archunit-junit5",               version.ref = "archunit"   }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
