<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>thelameres</groupId>
        <artifactId>txbox-producer</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>txbox-producer-starter</artifactId>
    <name>TxBox :: Producer :: Spring Boot Starter</name>
    <description>Auto-configuration: OutboxTemplate, OutboxPoller, OutboxMaintenance, OutboxHealthIndicator
    </description>

    <dependencies>
        <dependency>
            <groupId>thelameres</groupId>
            <artifactId>txbox-producer-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>thelameres</groupId>
            <artifactId>txbox-producer-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-liquibase</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-core</artifactId>
        </dependency>
    </dependencies>

</project>
