spring:
  application:
    name: txbox-full-example
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate

management:
  endpoint:
    health:
      show-details: always

txbox:
  producer:
    enabled: true
    kafka:
      routing: FIXED
      fixed-topic: domain.events
  consumer:
    # Пакеты для сканирования @DomainEvent классов.
    # Если не задано — fallback на пакеты из @SpringBootApplication.
    domain-event-base-packages:
      - com.somecompany.examples.event

logging:
  level:
    io:
      txbox: DEBUG
